### PR TITLE
chore: bump rust version in ci to 1.73.0

### PR DESCRIPTION
**Pull request by noot**
## Summary
bump rust version in ci to 1.73.0

## Background
required for #579; had to bump penumbra deps, which bumped libp2p, which requires rust >=1.73.0

## Changes
- bump rust version in ci to 1.73.0

### CODE REVIEW

**Comment by joroshiba** [comment]
We should update the docker images as well probably

**Review by sambukowski — APPROVED** [review]

**Comment by SuperFluffy** [comment]
This change and the bump to prost/prost-build 0.12 in #579 is currently blocked on protoc-gen-prost still being on prost 0.11.

**Review by SuperFluffy — CHANGES_REQUESTED** [review]
Requesting changes for 2 issues:

I would like to separate wider dependency bumps and feature PRs. This bump to 1.73 is explained by another PR, but ideally the reason for bumping should be tied to that PR.

But either way: I did prepare a PR bumping penumbra (and celestia) to their latest versions, which would allow us to use prost/prost-build 0.12 and tonic 0.10 (as does #579), but that is currently blocked on protoc-gen-prost still being on prost 0.11 (which we are using through buf).

This is an issue.

Other than forking protoc-gen-prost the only way to fix this is to move off `buf` temporarily. I am not sure how feasible it is to fork `protoc-gen-prost` because it would require us to somehow put the fork on buf and make it available to buf.

**Comment by noot** [comment]
@SuperFluffy okay, should i merge this PR into my IBC branch for now then? i figured the rust version bump would be separate enough for its own PR but either way is fine with me!

**Comment by SuperFluffy** [comment]
Closing this in favor of #581 (move away from buf) and #582 (bump all dependencies)

@noot these two should unblock #579

**Pull request closed without merging**
